name: CallBells
version: 1.0.0
main: net.callbells.CallBells
description: A Minecraft Paper plugin that allows players to opt in for chat warnings when a specific bell gets rung
author: Team Sneakymouse
website: https://rawb.tv
api-version: 1.19

dependencies:
  server:
    WorldEdit:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: false